sudo: required
services:
  - docker
before_install:
  - docker build -t ved13/reactapp -f Dockerfile.dev .
script:
  - docker run ved13/reactapp npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "dockerapp"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-621493105288"
  bucket_path: "dockerapp"
  on:
    branch: master

